@startuml
'https://plantuml.com/use-case-diagram
left to right direction
skinparam backgroundColor #E0F7FA
skinparam packageBackgroundColor #B2EBF2
skinparam packageBorderColor #00796B
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor #B2DFDB
    BorderColor #004D40
    FontColor #004D40
}
hide empty description

actor Staff as "👤 Staff"
actor Support as "👤 Support"

package "Support" {
    Staff -> (Suporte ao Cliente)
    Support -> (Suporte ao Cliente)
}

note right of Staff
    Staff auxilia na gestão de usuários e pets.
    - Auxílio no registro de pets
    - Auxílio nas consultas
end note

note right of Support
    Support fornece suporte ao cliente.
    - Suporte técnico
    - Atendimento ao cliente
end note


@enduml