server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false
  max-http-request-header-size:
    value: 10KB
  tomcat:
    connection-timeout: 2000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petshop?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: "root"
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'juliane.vmaran@gmail.com'
    password: 'equu xelx wfjj sgrd'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: 'juliane.vmaran@gmail.com'
  cloud:
    openfeign:
      client:
        default:
          connect-timeout: 5000
          read-timeout: 5000
          logger-level: full

debug: true

azure:
  url: 'https://petshop-web-api-a5aeanc2g5gzgzer.eastus2-01.azurewebsites.net/api'