spring:
  application:
    name: petshop-api
  profiles:
    active: local # prod
  devtools:
    restart:
      enabled: true
    add-properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      register-mbeans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  gson:
    date-format: "dd/MM/yyyy"
  jackson:
    locale: "pt_BR"
    time-zone: "America/Sao_Paulo"
    date-format: "dd/MM/yyyy"
    default-property-inclusion: "NON_NULL"
    property-naming-strategy: SNAKE_CASE
    serialization:
      INDENT_OUTPUT: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  messages:
    encoding: UTF-8
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  cache:
    type: simple

logging:
  file:
    name: "./logs/petshop-api.log"
  config: classpath:logback.xml
  charset:
    file: UTF-8
  include-application-name: true
  level:
    root: INFO
    sql: DEBUG
    web: DEBUG
  register-shutdown-hook: false
  pattern:
    level: "%X{user} %5p"
    date-format: "yyyy-MM-dd HH:mm"
    file: "%d{date-format} [%thread] %-5level %logger{36} - %msg%n"

info:
  app:
    artifactId: '@project.artifactId@'
    group: '@project.groupId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers,env,beans,mappings,openapi,swagger-ui"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  use-management-port: false
  default-consumes-media-type: application/json # request
  default-produces-media-type: application/json # response

petshop:
  jwt:
    expiration: 3600000 # 1 hora
    secret-key: "+9U02KQNo4tAmOX3YxXOyw5ydsdrIeqxo6PyuAMFosU="
  mail:
    from:
      name: 'PetFlow'
  via-cep:
    name: 'via-cep'
    url: 'https://viacep.com.br/ws/'