name: Build and deploy JAR app to Azure Web App - petshop-web-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server
          sudo service mysql start
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          sudo mysql -u root -p'root' -e "FLUSH PRIVILEGES;"
          sudo mysql -u root -p'root' -e "CREATE DATABASE IF NOT EXISTS petshop;"
          sudo mysql -u root -p'root' -e "DROP USER IF EXISTS 'root'@'localhost';"
          sudo mysql -u root -p'root' -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
          sudo mysql -u root -p'root' -e "GRANT ALL PRIVILEGES ON petshop.* TO 'root'@'localhost';"
          sudo mysql -u root -p'root' -e "FLUSH PRIVILEGES;"

      - name: Build with Maven
        run: |
          cd petshop-api
          mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'petshop-web-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1C1CC5F17D634E988DBE1C614F8E0AEA }}
          package: '*.jar'
